#!/bin/sh
# Test if it's not one of the system users
for u in root alpha beta
do
	if [ "$USER" == "$u" ]
	then
		exit 0;
	fi
done

# In case we are in close_session save the firefox profile
if [ -d /home/$USER/.mozilla ]
then
    cd /home/$USER/.mozilla;
    tar cvzf - firefox | ssh -K linux.mit.edu "cd ~/.mozilla; tar zxvf -;"
fi
